### PR TITLE
yakkety and zesty debs are now in old-releases.ubuntu.com

### PR DESCRIPTION
**Pull request by mikaelarguedas**

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Heh, I just made this change locally to afford building new images.

@tfoote and I also discovered that the available packages and index for yakkety have gone out of sync. So it isn't currently possible to generate new images for yakkety.

**Comment by nuclearsandwich** [comment]
Note that as of https://github.com/osrf/multiarch-docker-image-generation/commit/2208250b1155ef38f934c4a8557d3ec8cda96f1b none of the listed distros are supported by build_all.py. It may or may not make sense to prune or at least re-format that test _in a future change_.

edit: clarification of tense / immediate approval.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
Based on @nuclearsandwich's comment, this will not fix image generation for yakkety (and likely not zesty). But it is an incremental improvement even if this code is not used anymore as https://github.com/osrf/multiarch-docker-image-generation/commit/2208250b1155ef38f934c4a8557d3ec8cda96f1b removed EOL images from the build list

**Comment by nuclearsandwich** [comment]
> this will not fix image generation for yakkety (and likely not zesty)

I actually was able to build new zesty images with this change. But yakkety has upstream issues.

**Review by tfoote — APPROVED** [review]
lgtm, it does't hurt for this to work better on the old platforms. Even if yakkety is broken upstream at the moment this at least will get far enough to reproduce that.

**Pull request merged**
