### PR TITLE
Update static binaries to qemu 2.10 from qemu 2.1.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
These binaries were built on Ubuntu Xenial based on the sources in
qemu_2.10+dfsg-0ubuntu3.1

The binaries in the repository now are from qemu 2.1.93.

This hopes to address https://github.com/ros-infrastructure/ros_buildfarm/issues/214

I'm not sure what the best way to test these changes are. Is there a reasonable way to do a partial deployment?

### CODE REVIEW

**Comment by tfoote** [comment]
To test this these images could be built on a specific agent and that agent will persist the image in its local cache. I'm not sure how long it would last, it might get reaped by some of the disk space saving scripts but likely would last for several days on a fresh installation.

**Comment by nuclearsandwich** [comment]
Some test hosts have been deployed to the ROS buildfarm after smoke testing.

**Comment by nuclearsandwich** [comment]
These images did all pass the `nano` test, and the deployed hosts have not had any issues. However, I went to check in on the hosts and it appears that none of the new images have actually been used in running jobs.

Even though there are existing local images with the name:tag `osrf/ubuntu_arm64:xenial`, the "real" osrf/ubuntu_arm64:xenial is still pulled from Docker hub. The name is taken from the local image and given to the just downloaded one, which is used in all subsequent jobs.

The local containers running infinite loops to keep the images from being removed locally did their jobs, but were not sufficient for the local images to keep their association with the name.

**Comment by nuclearsandwich** [comment]
Tested locally with the following:

1. Set a custom tag on the prospective images, i.e. `docker tag `osrf/ubuntu_arm64:xenial test-ubuntu_arm64:xenial`
2. Generate a release script `generate_release_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml kinetic uxv8 catkin ubuntu xenial arm64`
3. Modify the release script to use the custom image tag
4. Run the release script and do a quick check of the package contents.

**Review by tfoote — APPROVED** [review]

**Comment by tfoote** [comment]
Before deploying these though we probably want to remove the EOL'd images from the build enumerations in the build all script.

**Pull request merged**
