### PR TITLE
Update binaries to qemu 2.11+dfsg-1ubuntu7.

### LINKED ISSUE #18: bionic: cannot run bash via qemu-arm-static/qemu-aarch64-static
The recent bionic sync fixed our glibc issue #17 but bash no longer runs via qemu.

There are several ways to reproduce the issue, the quickest is firing up our existing bionic image, updating the repository and installing the latest bash version from the repos.

During configure you'll see the result

```
bash: xmalloc: .././locale.c:81: cannot allocate 2 bytes (0 bytes allocated)
dpkg: error processing package bash (--configure):
 installed bash package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 bash
W: http: Running in qemu-user, not using seccomp
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@4bd3ec35b0af:/# bash
bash: xmalloc: .././locale.c:81: cannot allocate 2 bytes (0 bytes allocated)
```

You can also reproduce this in an x86_64 bionic container by installing qemu-user-static from the bionic repo, adding the arm64 repos and installing bash as an alternate architecture package. In docker containers binfmt doesn't update and this will uninstall your native bash package. But you can still run `qemu-aarch64-static $(which bash)` from your running shell and see the same error.

Edit: forgot to explicitly mention that this affects qemu 2.10 and qemu 2.11 (from bionic).

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Sourced from ubuntu bionic docker build 2018-02-19.

These were tested when investigating #18 They didn't resolve the issue but they work.

We don't need to accept the PR. We can decide to wait for a stable release of bionic or one which does address #18.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Does this mean that the builds are broken regardless of the image or does the current one work but is just outdated?
If the former I guess better have a newer one?
If the latter I would hold for a version that fixes #18 and keep the existing one in the meantime

**Comment by nuclearsandwich** [comment]
> Does this mean that the builds are broken regardless of the image or does the current one work but is just outdated?

The current binaries will work as well as these seem to. This was a tried upgrade path and the PR a documentation of that attempt. I don't believe that a qemu version bump will resolve #18 unless it brings support for position independent executables.

**Comment by nuclearsandwich** [comment]
It appears that there are some [bugs around seccomp behavior](https://bitbucket.org/osrf/release-tools/pull-requests/579/) fixed by qemu 2.11 that don't appear in the qemu 2.11 changelog. These bugs are likely to affect us on build.ros.org so I'd like to update the qemu version in our images before deploying the upgraded Docker agents.

**Comment by nuclearsandwich** [comment]
I've updated this PR with the qemu-{aarch64,arm}-static binaries from current bionic.

**Review by tfoote — APPROVED** [review]
This looks good to me. It would be great to have a way to introspect what version is embedded in the system. But I can't think of a good way to do that besides just keeping a readme up to date or something like that.

**Comment by nuclearsandwich** [comment]
> It would be great to have a way to introspect what version is embedded in the system. But I can't think of a good way to do that besides just keeping a readme up to date or something like that.

Where would you like to see that info? The file browser on GitHub shows the most recent commit to touch the file which now includes the version number. So it's available via browser. And to check the version locally (on a system that can run 64-bit linux binaries) running `./qemu-arm-static -version` will give the version number. We could add a note to the readme explaining the bundling of qemu binaries and how to tell the current version from the commit log. That would stay evergreen. I'm also not opposed to just adding the current qemu version to the readme and hoping that updates to that are caught during PR review.

**Comment by tfoote** [comment]
Yeah, if we make sure to be good about putting the full version into the commit that should be fine.

**Comment by nuclearsandwich** [comment]
Added a note to the readme about checking the version. There's some other elements in the README that could do with a re-touch so I'll open a follow up PR at a later date. For now merging this to deploy new images.

**Pull request merged**
